# Generated by Django 4.2.27 on 2026-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopost",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_picked", "Not Picked Up"),
                    ("collected", "Collected"),
                    ("delivered", "Delivered"),
                ],
                default="not_picked",
                max_length=20,
            ),
        ),
    ]
