# Generated by Django 4.2.27 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("pickup", "Pickup Collected"),
                    ("payment", "Payment Received"),
                    ("certificate", "Certificate Issued"),
                ],
                max_length=20,
            ),
        ),
    ]
