# Generated by Django 4.2.27 on 2025-12-31 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_clientprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("business_address", models.TextField()),
                ("contact_person", models.CharField(max_length=100)),
                ("alternate_phone", models.CharField(blank=True, max_length=15)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        default="vendor_profiles/default.png",
                        null=True,
                        upload_to="vendor_profiles/",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
