# Generated by Django 4.2.27 on 2025-12-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_vendordetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendordetails",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
