# Generated by Django 4.2.27 on 2025-12-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_vendordetails_latitude_vendordetails_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendordetails",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendordetails",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
